# Generated by Django 3.2.12 on 2022-03-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('clubID', models.AutoField(primary_key=True, serialize=False)),
                ('clubName', models.CharField(max_length=200)),
                ('clubLogo', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=200)),
                ('countryFlag', models.URLField(max_length=1000)),
            ],
            options={
                'ordering': ('countryName',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillsID', models.AutoField(primary_key=True, serialize=False)),
                ('prefferedFoot', models.CharField(max_length=10)),
                ('pace', models.IntegerField(default=0)),
                ('shooting', models.IntegerField(default=0)),
                ('passing', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('dribbling', models.IntegerField(default=0)),
                ('defending', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransferMarket',
            fields=[
                ('transferID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=10, null=True)),
                ('contractExpiry', models.IntegerField()),
                ('wages', models.CharField(max_length=10)),
                ('releaseClause', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=200)),
                ('playerAge', models.IntegerField(default=0)),
                ('playerPhoto', models.URLField(max_length=1000)),
                ('playerPosition', models.CharField(max_length=3)),
                ('playerClub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.club')),
                ('playerCountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.country')),
                ('playerValue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.transfermarket')),
                ('skills', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.skills')),
            ],
            options={
                'ordering': ('-skills__rating',),
            },
        ),
    ]
